name: Create Issue from Message

on:
  workflow_dispatch:
  repository_dispatch:
    types: [submit-message]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Issue
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/Alex-hwang/Alex-hwang.github.io/issues \
        -d "{\"title\": \"留言 from ${{ github.event.client_payload.name }}\", \"body\": \"**姓名**: ${{ github.event.client_payload.name }}\n**邮箱**: ${{ github.event.client_payload.email }}\n**留言**: ${{ github.event.client_payload.message }}\"}"
