name: Create Issue from Message

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Issue
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/Alex-hwang/Alex-hwang.github.io/issues \
        -d "{\"title\": \"留言 from ${{ github.event.issue.title }}\", \"body\": \"${{ github.event.issue.body }}\"}"
